### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by Waterski24** [nate-gray/KiL#18]
I'm imagining we make a default window that displays an error message, and whenever an exception is encountered, we just halt whatever was happening and display the message

**Comment by Waterski24** [comment]
Ideally, I think, we'd close the pop-up modal window that was open and display the error at the bottom of the screen. Seems least intrusive. I don't know how easy this would be though

**Comment by nate-gray** [comment]
**Violation:** Avoid throwing raw exception types. 
**Definition:** Avoid throwing certain exception types. Rather than throw a raw RuntimeException, Throwable, Exception, or Error, use a subclassed exception or error instead.

There are multiple instances throughout the code where we need to address this violation.  Rather than throwing Exception, we should be throwing specific exceptions for the context of that code.  We have a tech debt issue logged to address this issue.  In the current develop build, this violation occurs in these locations. 

AddNewLineItemController Line 89
AddToInventoryController Line 46
AddToInventoryController Line 55
AddToInventoryController Line 62
AmountUsedController Line 40

**Comment by Waterski24** [comment]
should be all handled in my latest pull request
